---
exclude: ipython_config.py
repos:
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/zahorniak/pre-commit-circleci
    rev: v0.2
    hooks:
      - id: circleci_validate
        name: circleci
