---
name: test
namespace: test
engine: ~2
public:
  retries: true
healthcheck:
  liveness:
    path: /live
  readiness:
    path: /ready
scale:
  horizontal: 3-20
  cpuNoLimits: true
  cpuThreshold: 65
  vertical: medium.mem2x

dependencies:
  redis:
    version: 16.9.3
    repo: "@bitnami"
    settings:
      fullnameOverride: redis
      architecture: standalone
      master:
        persistence:
          size: 50Gi
        livenessProbe:
          initialDelaySeconds: 200
        readinessProbe:
          initialDelaySeconds: 200
        resources:
          requests:
            memory: "8Gi"
            cpu: "250m"
          limits:
            memory: "8Gi"
  mongodb:
    version: 10.11.0
    repo: "@bitnami"
    settings:
      useStatefulSet: true
      fullnameOverride: mongodb
      auth:
        enabled: false
  elasticsearch:
    repo: "@elastic"
    version: 7.17.3
    settings:
      clusterName: snowstorm
      replicas: 2
      esJavaOpts: "-Xmx2g -Xms2g"
      resources:
        requests:
          cpu: "125m"
          memory: "4Gi"
        limits:
          cpu: null
          memory: "4Gi"
  other:
    version: 7.7.0
    repo: "abracadabra"
    settings:
      clusterName: snowstorm
      replicas: 2
      esJavaOpts: "-Xmx2g -Xms2g"
      resources:
        requests:
          cpu: "125m"
          memory: "4Gi"
        limits:
          cpu: null
          memory: "4Gi"
